name: DevOps Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore ArticleService/ArticleService.csproj
          dotnet restore CommentService/CommentService.csproj

      - name: Build ArticleService
        run: |
          dotnet build ArticleService/ArticleService.csproj --configuration Release --no-restore

      - name: Build CommentService
        run: |
          dotnet build CommentService/CommentService.csproj --configuration Release --no-restore

      - name: Collect executables
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: |
            ArticleService/bin/Release/
            CommentService/bin/Release/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(date +%Y%m%d%H%M%S)-${{ github.sha }}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Debug: VERSION=$VERSION"

      - name: Build and push ArticleService Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ArticleService/Dockerfile
          push: true
          tags: ghcr.io/sunwar01/happyheadlinescompulsoryassignment/articleservice:${{ env.VERSION }}
          platforms: linux/amd64

      - name: Build and push CommentService Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./CommentService/Dockerfile
          push: true
          tags: ghcr.io/sunwar01/happyheadlinescompulsoryassignment/commentservice:${{ env.VERSION }}
          platforms: linux/amd64